import {
  AcademicHoliday,
  AttendanceCorrectionRequest,
  AttendanceRecord,
  AttendanceSession,
  AuditLog,
  Branch,
  CollegeSettings,
  Division,
  LeaveApplication,
  Lecture,
  Notification,
  Room,
  Subject,
  User,
} from './types';

export const initialSettings: CollegeSettings = {
  collegeName: 'Apex Institute of Technology & Science',
  collegeShortName: 'AITS University',
  academicYear: '2026-2027',
  currentSemesterTerm: 'Autumn Semester 2026',
  minAttendanceThreshold: 75,
  warningThreshold: 65,
  qrExpirySeconds: 120, // 2 minutes server-side expiration
  allowWifiRestriction: true,
  collegeWifiSsid: 'Campus_AITS_Secure_5G',
  allowGpsRestriction: false,
  campusLatitude: 12.9716,
  campusLongitude: 77.5946,
  campusRadiusMeters: 500,
};

export const initialBranches: Branch[] = [
  {
    id: 'branch_cs',
    code: 'CSE',
    name: 'Computer Science & Engineering',
    department: 'School of Computing',
  },
  {
    id: 'branch_ece',
    code: 'ECE',
    name: 'Electronics & Communication Engineering',
    department: 'School of Electrical Sciences',
  },
];

export const initialDivisions: Division[] = [
  { id: 'div_cs_3a', name: 'A', branchId: 'branch_cs', semester: 3 },
  { id: 'div_cs_3b', name: 'B', branchId: 'branch_cs', semester: 3 },
  { id: 'div_cs_5a', name: 'A', branchId: 'branch_cs', semester: 5 },
  { id: 'div_ece_3a', name: 'A', branchId: 'branch_ece', semester: 3 },
];

export const initialRooms: Room[] = [
  {
    id: 'room_c204',
    code: 'Room C-204',
    name: 'Turing Hall C-204',
    type: 'lecture_hall',
    capacity: 70,
    building: 'Computing Sciences Block',
    floor: '2nd Floor',
  },
  {
    id: 'room_b102',
    code: 'Room B-102',
    name: 'Lovelace Lecture Hall B-102',
    type: 'lecture_hall',
    capacity: 65,
    building: 'Computing Sciences Block',
    floor: '1st Floor',
  },
  {
    id: 'lab_turing',
    code: 'Lab 2',
    name: 'Turing Advanced Software Lab',
    type: 'lab',
    capacity: 45,
    building: 'Computing Sciences Block',
    floor: 'Ground Floor',
  },
  {
    id: 'room_a301',
    code: 'Room A-301',
    name: 'Shannon Amphitheater A-301',
    type: 'seminar',
    capacity: 120,
    building: 'Central Academic Block',
    floor: '3rd Floor',
  },
  {
    id: 'lab_ece5',
    code: 'Lab 5',
    name: 'Embedded Systems & DSP Lab',
    type: 'lab',
    capacity: 40,
    building: 'Electronics Block',
    floor: '2nd Floor',
  },
];

export const initialUsers: User[] = [
  // Admin
  {
    id: 'user_admin_1',
    name: 'Dean Robert Sterling',
    email: 'dean.sterling@aits.edu',
    role: 'admin',
    department: 'Office of Academic Affairs & Registrar',
    phone: '+1 (555) 839-2001',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  },
  // Professors
  {
    id: 'prof_1',
    name: 'Dr. Vikram Roy',
    email: 'vikram.roy@aits.edu',
    role: 'professor',
    department: 'Computer Science & Engineering',
    professorId: 'PROF-CS-101',
    designation: 'Professor & Head of Computing',
    specialization: 'Discrete Mathematics & Algorithmic Analysis',
    phone: '+1 (555) 301-4491',
    assignedSubjectIds: ['subj_math', 'subj_algo'],
    assignedDivisions: ['A', 'B'],
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'prof_2',
    name: 'Prof. Sarah Jenkins',
    email: 'sarah.jenkins@aits.edu',
    role: 'professor',
    department: 'Computer Science & Engineering',
    professorId: 'PROF-CS-102',
    designation: 'Associate Professor',
    specialization: 'Distributed Database Systems & Storage',
    phone: '+1 (555) 301-4492',
    assignedSubjectIds: ['subj_dbms', 'subj_os'],
    assignedDivisions: ['A'],
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'prof_3',
    name: 'Dr. Rajesh Kothari',
    email: 'rajesh.kothari@aits.edu',
    role: 'professor',
    department: 'Computer Science & Engineering',
    professorId: 'PROF-CS-103',
    designation: 'Assistant Professor',
    specialization: 'Object Oriented Paradigms & Distributed Networks',
    phone: '+1 (555) 301-4493',
    assignedSubjectIds: ['subj_oop'],
    assignedDivisions: ['A', 'B'],
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'prof_4',
    name: 'Dr. Alistair Vance',
    email: 'alistair.vance@aits.edu',
    role: 'professor',
    department: 'Electronics & Communication',
    professorId: 'PROF-ECE-201',
    designation: 'Professor',
    specialization: 'Digital Signal Processing & Microcontrollers',
    phone: '+1 (555) 301-4494',
    assignedSubjectIds: ['subj_dsp'],
    assignedDivisions: ['A'],
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'prof_5',
    name: 'Prof. Meera Nair',
    email: 'meera.nair@aits.edu',
    role: 'professor',
    department: 'Computer Science & Engineering',
    professorId: 'PROF-CS-104',
    designation: 'Assistant Professor',
    specialization: 'AI Systems & Modern Web Architectures',
    phone: '+1 (555) 301-4495',
    assignedSubjectIds: ['subj_ai', 'subj_web'],
    assignedDivisions: ['A'],
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=256',
  },

  // 20 Realistic Students
  {
    id: 'stud_1',
    name: 'Aaryan Sharma',
    email: 'aaryan.sharma@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-001',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    phone: '+1 (555) 782-9011',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_2',
    name: 'Priya Patel',
    email: 'priya.patel@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-002',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    phone: '+1 (555) 782-9012',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_3',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-003',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_4',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-004',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_5',
    name: 'Devansh Verma',
    email: 'devansh.verma@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-005',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_6',
    name: 'Ishita Sen',
    email: 'ishita.sen@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-006',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_7',
    name: 'Kabir Mehta',
    email: 'kabir.mehta@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-007',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_8',
    name: 'Tanvi Reddy',
    email: 'tanvi.reddy@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-008',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_9',
    name: 'Siddharth Rao',
    email: 'siddharth.rao@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-009',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_10',
    name: 'Sneha Joshi',
    email: 'sneha.joshi@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-010',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_11',
    name: 'Aditya Nair',
    email: 'aditya.nair@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-011',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_12',
    name: 'Riya Kapoor',
    email: 'riya.kapoor@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-012',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    avatarUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'stud_13',
    name: 'Manan Desai',
    email: 'manan.desai@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-013',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'B',
  },
  {
    id: 'stud_14',
    name: 'Pooja Bhatia',
    email: 'pooja.bhatia@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-014',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'B',
  },
  {
    id: 'stud_15',
    name: 'Varun Chopra',
    email: 'varun.chopra@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-015',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'B',
  },
  {
    id: 'stud_16',
    name: 'Diya Saxena',
    email: 'diya.saxena@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2024-016',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 3,
    division: 'B',
  },
  {
    id: 'stud_17',
    name: 'Karan Singhania',
    email: 'karan.singhania@student.aits.edu',
    role: 'student',
    enrollmentNo: 'EC-2024-001',
    department: 'Electronics & Communication',
    branchId: 'branch_ece',
    semester: 3,
    division: 'A',
  },
  {
    id: 'stud_18',
    name: 'Natasha Joseph',
    email: 'natasha.joseph@student.aits.edu',
    role: 'student',
    enrollmentNo: 'EC-2024-002',
    department: 'Electronics & Communication',
    branchId: 'branch_ece',
    semester: 3,
    division: 'A',
  },
  {
    id: 'stud_19',
    name: 'Arjun Malhotra',
    email: 'arjun.malhotra@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2023-001',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 5,
    division: 'A',
  },
  {
    id: 'stud_20',
    name: 'Bhavna Pillai',
    email: 'bhavna.pillai@student.aits.edu',
    role: 'student',
    enrollmentNo: 'CS-2023-002',
    department: 'Computer Science & Engineering',
    branchId: 'branch_cs',
    semester: 5,
    division: 'A',
  },
];

export const initialSubjects: Subject[] = [
  {
    id: 'subj_math',
    code: 'CS-301',
    name: 'Engineering Mathematics III',
    branchId: 'branch_cs',
    semester: 3,
    credits: 4,
    professorId: 'prof_1',
    color: '#3B82F6', // Electric Blue
  },
  {
    id: 'subj_dbms',
    code: 'CS-302',
    name: 'Database Management Systems',
    branchId: 'branch_cs',
    semester: 3,
    credits: 4,
    professorId: 'prof_2',
    color: '#8B5CF6', // Purple
  },
  {
    id: 'subj_algo',
    code: 'CS-303',
    name: 'Design & Analysis of Algorithms',
    branchId: 'branch_cs',
    semester: 3,
    credits: 4,
    professorId: 'prof_1',
    color: '#06B6D4', // Cyan
  },
  {
    id: 'subj_os',
    code: 'CS-304',
    name: 'Operating Systems & Kernel Design',
    branchId: 'branch_cs',
    semester: 3,
    credits: 3,
    professorId: 'prof_2',
    color: '#EC4899', // Pink
  },
  {
    id: 'subj_oop',
    code: 'CS-305',
    name: 'Object Oriented Programming (Java)',
    branchId: 'branch_cs',
    semester: 3,
    credits: 4,
    professorId: 'prof_3',
    color: '#10B981', // Emerald Green
  },
  {
    id: 'subj_ai',
    code: 'CS-306',
    name: 'Artificial Intelligence Fundamentals',
    branchId: 'branch_cs',
    semester: 3,
    credits: 3,
    professorId: 'prof_5',
    color: '#F59E0B', // Amber
  },
  {
    id: 'subj_web',
    code: 'CS-307',
    name: 'Modern Full-Stack Web Architecture',
    branchId: 'branch_cs',
    semester: 3,
    credits: 3,
    professorId: 'prof_5',
    color: '#6366F1', // Indigo
  },
  {
    id: 'subj_dsp',
    code: 'EC-301',
    name: 'Digital Signal Processing',
    branchId: 'branch_ece',
    semester: 3,
    credits: 4,
    professorId: 'prof_4',
    color: '#14B8A6', // Teal
  },
];

// Current Date in our scenario: 2026-09-24 (Thursday)
export const initialLectures: Lecture[] = [
  // Thursday 2026-09-24 (TODAY) for CS Sem 3 Div A
  {
    id: 'LEC-2026-09-24-CS-3A-OOP-01',
    date: '2026-09-24',
    startTime: '09:00',
    endTime: '10:00',
    subjectId: 'subj_oop',
    professorId: 'prof_3',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
    topic: 'Java Generics, Wildcards & Collections Framework',
  },
  {
    id: 'LEC-2026-09-24-CS-3A-MATH-02',
    date: '2026-09-24',
    startTime: '10:00',
    endTime: '11:00',
    subjectId: 'subj_math',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'scheduled', // Active Next Lecture for today
    topic: 'Fourier Transforms & Boundary Value Problems',
  },
  {
    id: 'LEC-2026-09-24-CS-3A-DBMS-03',
    date: '2026-09-24',
    startTime: '11:15',
    endTime: '12:15',
    subjectId: 'subj_dbms',
    professorId: 'prof_2',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'scheduled',
    topic: 'Query Optimization & B+ Tree Indexing Internals',
  },
  {
    id: 'LEC-2026-09-24-CS-3A-ALGO-04',
    date: '2026-09-24',
    startTime: '13:00',
    endTime: '14:00',
    subjectId: 'subj_algo',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'scheduled',
    topic: 'Dynamic Programming vs Greedy: Knapsack & Matrix Chain',
  },
  {
    id: 'LEC-2026-09-24-CS-3A-LAB-05',
    date: '2026-09-24',
    startTime: '14:15',
    endTime: '16:15',
    subjectId: 'subj_dbms',
    professorId: 'prof_2',
    roomId: 'lab_turing',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'scheduled',
    topic: 'Lab Practicum 4: Transaction Isolation & ACID benchmarking',
  },

  // Friday 2026-09-25 (TOMORROW)
  {
    id: 'LEC-2026-09-25-CS-3A-OS-01',
    date: '2026-09-25',
    startTime: '09:00',
    endTime: '10:00',
    subjectId: 'subj_os',
    professorId: 'prof_2',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'scheduled',
    topic: 'Virtual Memory, TLB Paging & Page Replacement Algorithms',
  },
  {
    id: 'LEC-2026-09-25-CS-3A-AI-02',
    date: '2026-09-25',
    startTime: '10:00',
    endTime: '11:00',
    subjectId: 'subj_ai',
    professorId: 'prof_5',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'scheduled',
    topic: 'A* Heuristic Search & Adversarial Minimax with Alpha-Beta',
  },
  {
    id: 'LEC-2026-09-25-CS-3A-WEB-03',
    date: '2026-09-25',
    startTime: '11:15',
    endTime: '12:15',
    subjectId: 'subj_web',
    professorId: 'prof_5',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'scheduled',
    topic: 'WebSockets, Real-time Protocols & Micro-frontends',
  },

  // Historical Conducted Lectures for CS-3A (Past few weeks for realistic statistics)
  // Week 1 to Week 3 lectures
  {
    id: 'LEC-2026-09-23-CS-3A-MATH-01',
    date: '2026-09-23',
    startTime: '10:00',
    endTime: '11:00',
    subjectId: 'subj_math',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
    topic: 'Laplace Transform Applications in Differential Equations',
  },
  {
    id: 'LEC-2026-09-23-CS-3A-DBMS-01',
    date: '2026-09-23',
    startTime: '11:15',
    endTime: '12:15',
    subjectId: 'subj_dbms',
    professorId: 'prof_2',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
    topic: 'Relational Algebra & Normalization (3NF & BCNF)',
  },
  {
    id: 'LEC-2026-09-22-CS-3A-OOP-01',
    date: '2026-09-22',
    startTime: '09:00',
    endTime: '10:00',
    subjectId: 'subj_oop',
    professorId: 'prof_3',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
    topic: 'Polymorphism & Interface Segregation in Java',
  },
  {
    id: 'LEC-2026-09-22-CS-3A-ALGO-01',
    date: '2026-09-22',
    startTime: '13:00',
    endTime: '14:00',
    subjectId: 'subj_algo',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
    topic: 'Divide & Conquer Recurrences: Master Theorem',
  },
  {
    id: 'LEC-2026-09-21-CS-3A-MATH-01',
    date: '2026-09-21',
    startTime: '10:00',
    endTime: '11:00',
    subjectId: 'subj_math',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
    topic: 'Eigenvalues, Eigenvectors & Cayley-Hamilton',
  },
  {
    id: 'LEC-2026-09-21-CS-3A-OS-01',
    date: '2026-09-21',
    startTime: '11:15',
    endTime: '12:15',
    subjectId: 'subj_os',
    professorId: 'prof_2',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
    topic: 'Process Scheduling & Mutex Concurrency',
  },
  {
    id: 'LEC-2026-09-18-CS-3A-DBMS-01',
    date: '2026-09-18',
    startTime: '11:15',
    endTime: '12:15',
    subjectId: 'subj_dbms',
    professorId: 'prof_2',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-18-CS-3A-ALGO-01',
    date: '2026-09-18',
    startTime: '13:00',
    endTime: '14:00',
    subjectId: 'subj_algo',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-17-CS-3A-MATH-01',
    date: '2026-09-17',
    startTime: '10:00',
    endTime: '11:00',
    subjectId: 'subj_math',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-16-CS-3A-OOP-01',
    date: '2026-09-16',
    startTime: '09:00',
    endTime: '10:00',
    subjectId: 'subj_oop',
    professorId: 'prof_3',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-15-CS-3A-MATH-01',
    date: '2026-09-15',
    startTime: '10:00',
    endTime: '11:00',
    subjectId: 'subj_math',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-15-CS-3A-OS-01',
    date: '2026-09-15',
    startTime: '11:15',
    endTime: '12:15',
    subjectId: 'subj_os',
    professorId: 'prof_2',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-14-CS-3A-ALGO-01',
    date: '2026-09-14',
    startTime: '13:00',
    endTime: '14:00',
    subjectId: 'subj_algo',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-11-CS-3A-MATH-01',
    date: '2026-09-11',
    startTime: '10:00',
    endTime: '11:00',
    subjectId: 'subj_math',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-10-CS-3A-DBMS-01',
    date: '2026-09-10',
    startTime: '11:15',
    endTime: '12:15',
    subjectId: 'subj_dbms',
    professorId: 'prof_2',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-09-CS-3A-OOP-01',
    date: '2026-09-09',
    startTime: '09:00',
    endTime: '10:00',
    subjectId: 'subj_oop',
    professorId: 'prof_3',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-08-CS-3A-MATH-01',
    date: '2026-09-08',
    startTime: '10:00',
    endTime: '11:00',
    subjectId: 'subj_math',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-07-CS-3A-ALGO-01',
    date: '2026-09-07',
    startTime: '13:00',
    endTime: '14:00',
    subjectId: 'subj_algo',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-04-CS-3A-MATH-01',
    date: '2026-09-04',
    startTime: '10:00',
    endTime: '11:00',
    subjectId: 'subj_math',
    professorId: 'prof_1',
    roomId: 'room_c204',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
  {
    id: 'LEC-2026-09-03-CS-3A-DBMS-01',
    date: '2026-09-03',
    startTime: '11:15',
    endTime: '12:15',
    subjectId: 'subj_dbms',
    professorId: 'prof_2',
    roomId: 'room_b102',
    branchId: 'branch_cs',
    semester: 3,
    division: 'A',
    status: 'conducted',
  },
];

// Helper to seed attendance records for historical conducted lectures
function generateInitialAttendance(): AttendanceRecord[] {
  const records: AttendanceRecord[] = [];
  const conductedLectures = initialLectures.filter((l) => l.status === 'conducted');

  // Student 1 (Aaryan Sharma): High attendance ~87%
  // Student 2 (Priya Patel): Low attendance ~68%
  // Other students have realistic varying attendances
  conductedLectures.forEach((lec, idx) => {
    // 09:00 class today: Aaryan was present
    const isTodayMorning = lec.id === 'LEC-2026-09-24-CS-3A-OOP-01';

    // Aaryan Sharma (stud_1)
    let stud1Status: 'present' | 'absent' | 'approved_leave' = 'present';
    if (idx === 2) stud1Status = 'absent';
    else if (idx === 5) stud1Status = 'approved_leave'; // 2 approved leaves
    else if (idx === 10) stud1Status = 'approved_leave';
    else if (idx === 13) stud1Status = 'absent';

    records.push({
      id: `att-rec-${lec.id}-stud_1`,
      lectureId: lec.id,
      studentId: 'stud_1',
      status: isTodayMorning ? 'present' : stud1Status,
      markedAt: `${lec.date}T${lec.startTime}:12.000Z`,
      markedBy: isTodayMorning ? 'qr' : 'qr',
      deviceInfo: 'iOS Mobile / Safari 18',
      ipAddress: '192.168.1.104',
    });

    // Priya Patel (stud_2): More absents to test Low Attendance Warning!
    let stud2Status: 'present' | 'absent' | 'approved_leave' = 'present';
    if (idx % 3 === 0 || idx === 1 || idx === 7 || idx === 11) {
      stud2Status = 'absent';
    } else if (idx === 4) {
      stud2Status = 'approved_leave';
    }

    records.push({
      id: `att-rec-${lec.id}-stud_2`,
      lectureId: lec.id,
      studentId: 'stud_2',
      status: isTodayMorning ? 'absent' : stud2Status,
      markedAt: `${lec.date}T${lec.startTime}:15.000Z`,
      markedBy: 'qr',
      deviceInfo: 'Android Chrome 128',
    });

    // Other students 3 to 12 in Div A
    for (let s = 3; s <= 12; s++) {
      const studentId = `stud_${s}`;
      const isAbsent = (idx + s) % 7 === 0;
      records.push({
        id: `att-rec-${lec.id}-${studentId}`,
        lectureId: lec.id,
        studentId,
        status: isAbsent ? 'absent' : 'present',
        markedAt: `${lec.date}T${lec.startTime}:20.000Z`,
        markedBy: 'qr',
      });
    }
  });

  return records;
}

export const initialAttendanceRecords: AttendanceRecord[] = generateInitialAttendance();

// Active / Initial QR Attendance Sessions
export const initialAttendanceSessions: AttendanceSession[] = [
  {
    id: 'session_active_math_today',
    lectureId: 'LEC-2026-09-24-CS-3A-MATH-02',
    professorId: 'prof_1',
    sessionToken: 'NEXUS-TOKEN-MATH-7729-ALPHA',
    createdAt: new Date().toISOString(),
    // 2 minutes validity
    expiresAt: new Date(Date.now() + 120 * 1000).toISOString(),
    status: 'active',
    requireWifi: true,
    allowedWifiSsid: 'Campus_AITS_Secure_5G',
  },
];

export const initialLeaveApplications: LeaveApplication[] = [
  {
    id: 'leave_app_01',
    studentId: 'stud_1',
    subjectId: 'subj_math',
    professorId: 'prof_1',
    startDate: '2026-09-21',
    endDate: '2026-09-21',
    lectureIds: ['LEC-2026-09-21-CS-3A-MATH-01'],
    reason: 'Representing university at National Inter-College Hackathon Finals',
    documentName: 'Hackathon_Invitation_Letter.pdf',
    status: 'approved',
    reviewNote: 'Approved. Hackathon representation granted on duty leave.',
    appliedAt: '2026-09-19T14:30:00Z',
    reviewedAt: '2026-09-20T09:15:00Z',
    reviewedBy: 'Dr. Vikram Roy',
  },
  {
    id: 'leave_app_02',
    studentId: 'stud_1',
    subjectId: 'subj_algo',
    professorId: 'prof_1',
    startDate: '2026-09-28',
    endDate: '2026-09-29',
    lectureIds: [],
    reason: 'Medical consultation for severe sinus infection',
    documentName: 'Medical_Certificate_Aaryan.pdf',
    status: 'pending',
    appliedAt: '2026-09-23T18:00:00Z',
  },
  {
    id: 'leave_app_03',
    studentId: 'stud_2',
    subjectId: 'subj_dbms',
    professorId: 'prof_2',
    startDate: '2026-09-22',
    endDate: '2026-09-22',
    lectureIds: [],
    reason: 'Family emergency / out of station travel',
    status: 'pending',
    appliedAt: '2026-09-23T20:10:00Z',
  },
];

export const initialAttendanceCorrections: AttendanceCorrectionRequest[] = [
  {
    id: 'corr_01',
    studentId: 'stud_1',
    lectureId: 'LEC-2026-09-22-CS-3A-ALGO-01',
    professorId: 'prof_1',
    requestedStatus: 'present',
    reason: 'Phone battery drained before QR code scanned, was present in row 3.',
    proofNote: 'Professor verified lab notebook notes from same session.',
    status: 'pending',
    createdAt: '2026-09-23T11:00:00Z',
  },
];

export const initialNotifications: Notification[] = [
  // Student 1 Notifications
  {
    id: 'notif_1',
    userId: 'stud_1',
    role: 'student',
    title: 'Attendance Confirmed',
    message: 'Your attendance for CS-305 (Object Oriented Programming) was marked PRESENT via QR.',
    type: 'attendance',
    read: false,
    link: '/student/attendance',
    createdAt: '2026-09-24T09:05:00Z',
  },
  {
    id: 'notif_2',
    userId: 'stud_1',
    role: 'student',
    title: 'Upcoming Lecture Notice',
    message: 'CS-301 Engineering Mathematics starts at 10:00 AM in Room C-204 with Dr. Vikram Roy.',
    type: 'timetable',
    read: false,
    link: '/student/timetable',
    createdAt: '2026-09-24T09:45:00Z',
  },
  {
    id: 'notif_3',
    userId: 'stud_1',
    role: 'student',
    title: 'Duty Leave Approved',
    message: 'Your leave application for Hackathon Finals on Sep 21 has been APPROVED by Dr. Vikram Roy.',
    type: 'leave',
    read: true,
    link: '/student/leaves',
    createdAt: '2026-09-20T09:20:00Z',
  },
  // Student 2 Low Attendance Warning Notification
  {
    id: 'notif_4',
    userId: 'stud_2',
    role: 'student',
    title: 'Low Attendance Warning',
    message: 'Your overall attendance is 68.42% (below 75% minimum requirement). Please review recovery plan.',
    type: 'alert',
    read: false,
    link: '/student/attendance',
    createdAt: '2026-09-24T09:10:00Z',
  },
  // Professor 1 Notifications
  {
    id: 'notif_5',
    userId: 'prof_1',
    role: 'professor',
    title: 'Pending Leave Application',
    message: 'Aaryan Sharma submitted a leave request for Sep 28 - Sep 29.',
    type: 'leave',
    read: false,
    link: '/professor/leaves',
    createdAt: '2026-09-23T18:05:00Z',
  },
  {
    id: 'notif_6',
    userId: 'prof_1',
    role: 'professor',
    title: 'Attendance Correction Request',
    message: 'Aaryan Sharma requested attendance correction for Algorithms on Sep 22.',
    type: 'attendance',
    read: false,
    link: '/professor/corrections',
    createdAt: '2026-09-23T11:05:00Z',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'audit_01',
    timestamp: '2026-09-24T09:00:10Z',
    actorId: 'prof_3',
    actorName: 'Dr. Rajesh Kothari',
    actorRole: 'professor',
    action: 'STARTED_ATTENDANCE_SESSION',
    entity: 'AttendanceSession',
    entityId: 'LEC-2026-09-24-CS-3A-OOP-01',
    details: 'Initiated 2-minute dynamic QR attendance session for Division A',
  },
  {
    id: 'audit_02',
    timestamp: '2026-09-20T09:15:00Z',
    actorId: 'prof_1',
    actorName: 'Dr. Vikram Roy',
    actorRole: 'professor',
    action: 'APPROVED_LEAVE_APPLICATION',
    entity: 'LeaveApplication',
    entityId: 'leave_app_01',
    details: 'Granted duty leave for Aaryan Sharma (Inter-college Hackathon)',
  },
  {
    id: 'audit_03',
    timestamp: '2026-09-18T16:00:00Z',
    actorId: 'user_admin_1',
    actorName: 'Dean Robert Sterling',
    actorRole: 'admin',
    action: 'UPDATED_COLLEGE_SETTINGS',
    entity: 'CollegeSettings',
    entityId: 'settings',
    details: 'Enforced 75% attendance threshold with 120s QR session TTL',
  },
];

export const initialHolidays: AcademicHoliday[] = [
  {
    id: 'hol_01',
    title: 'University Founders Day',
    date: '2026-10-02',
    type: 'holiday',
    description: 'National & University Holiday',
  },
  {
    id: 'hol_02',
    title: 'Mid-Semester Examinations Term I',
    date: '2026-10-15',
    type: 'exam',
    description: 'Autonomous Mid-Term Examination Week',
  },
  {
    id: 'hol_03',
    title: 'Autumn Cultural & Tech Fest (AETHER 2026)',
    date: '2026-10-24',
    type: 'event',
    description: 'Annual Intercollegiate Technology Symposium',
  },
];
